# Generated by Django 4.2.5 on 2024-02-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("unique_id", models.IntegerField()),
                ("unique_uuid", models.CharField(max_length=36)),
                ("origin_unique_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorSocialMediaContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.IntegerField()),
                ("unique_uuid", models.CharField(max_length=36)),
                ("origin_unique_id", models.CharField(max_length=255)),
                ("creation_info_created_at", models.DateTimeField()),
                ("creation_info_timestamp", models.DateTimeField()),
                ("main_text", models.TextField()),
                ("token_count", models.IntegerField()),
                ("char_count", models.IntegerField()),
                ("tag_count", models.IntegerField()),
                ("origin_url", models.URLField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_contents",
                        to="social_media.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMediaPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("Instagram", "Instagram"), ("TikTok", "TikTok")],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorSocialPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("profile_text", models.TextField()),
                ("avatar_url", models.URLField()),
                ("followers_id", models.IntegerField()),
                ("followers_count", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_platforms",
                        to="social_media.author",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_social_platforms",
                        to="social_media.socialmediaplatform",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorSocialMediaStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes_id", models.IntegerField()),
                ("likes_count", models.IntegerField()),
                ("views_id", models.IntegerField()),
                ("views_count", models.IntegerField()),
                ("comments_id", models.IntegerField()),
                ("comments_count", models.IntegerField()),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_stats",
                        to="social_media.authorsocialmediacontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorSocialMediaContentMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_url", models.URLField()),
                ("media_type", models.CharField(max_length=50)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_contents",
                        to="social_media.author",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_content",
                        to="social_media.authorsocialmediacontent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="authorsocialmediacontent",
            name="origin_platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_origin_platforms",
                to="social_media.socialmediaplatform",
            ),
        ),
    ]
