# Generated by Django 4.2.5 on 2024-02-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0002_alter_authorsocialmediacontent_char_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="origin_unique_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="unique_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="author",
            name="unique_uuid",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
