# Generated by Django 4.2.5 on 2024-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "social_media",
            "0003_alter_author_origin_unique_id_alter_author_unique_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorsocialmediacontent",
            name="main_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
