# Generated by Django 4.2.5 on 2024-02-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0005_alter_authorsocialmediacontent_origin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorsocialmediacontentmedia",
            name="media_url",
            field=models.TextField(),
        ),
    ]
