repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.263"
    hooks:
      - id: ruff
        exclude: |
          (?x)^(tests/.*|.*/migrations/.*|.*/models/__init__.py)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
